#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "ORCID":
      - "https://orcid.org/0000-0002-8544-2240"
    "LinkedIn":
      - "https://www.linkedin.com/in/remi-rateau"
    "ResearchGate":
      - "https://www.researchgate.net/profile/Remi_Rateau"

color_scheme: rec-dark.scss

# defaults
defaults:
  - scope:
      path: ""
    values:
      image: ""

# jekyll-seo-tag

title: Rare Earth Carbonates
tagline: "All about rare earth carbonates"
description: "A compedium of useful resources and data on rare earth carbonates for the geologist and geochemist."
type: website

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/images/rec-logo.png"

# enable theme for local usage
#theme: "just-the-docs"
